export type UserRole = 'hrd' | 'karyawan' | 'manajemen';

export interface User {
  user_id: string;
  username: string;
  password?: string;
  role: UserRole;
  employee_id?: string; // Connected employee
}

export interface Employee {
  employee_id: string;
  nama: string;
  jabatan: string;
  departemen: string;
  potential: 'high' | 'medium' | 'low'; // Potential score for 9-Box Matrix (calculated or inputted)
}

export interface AssessmentPeriod {
  period_id: string;
  name: string;
  start_date: string;
  end_date: string;
  status: 'active' | 'closed';
}

export interface EmployeeRelation {
  relation_id: string;
  assessor_id: string;   // Employee ID who assesses
  assessed_id: string;   // Employee ID who is being assessed
  relation_type: 'atasan' | 'peer' | 'bawahan';
}

export interface CoreValueDetail {
  id: string;
  name: string; // Amanah, Kompeten, Harmonis, Loyal, Adaptif, Kolaboratif
  description: string;
}

export interface Assessment {
  assessment_id: string;
  assessor_id: string;   // Employee ID who assesses
  assessed_id: string;   // Employee ID who is being assessed
  period_id: string;
  relation_type: 'self' | 'atasan' | 'peer' | 'bawahan';
  scores: {
    amanah: number;       // 1 - 5
    kompeten: number;     // 1 - 5
    harmonis: number;     // 1 - 5
    loyal: number;        // 1 - 5
    adaptif: number;      // 1 - 5
    kolaboratif: number;  // 1 - 5
  };
  notes?: string;
  status: 'draft' | 'submitted';
  submitted_at?: string;
}

export interface IDP {
  idp_id: string;
  employee_id: string;
  period_id: string;
  strengths: string[];
  weaknesses: string[];
  recommendations: string[]; // generated by Gemini or inputted
  created_at: string;
}

export interface Notification {
  notification_id: string;
  employee_id: string;
  title: string;
  message: string;
  is_read: boolean;
  created_at: string;
}

// Aggregated results structure
export interface AssessmentResult {
  employee_id: string;
  period_id: string;
  scoresByRelation: {
    self: Record<string, number>;
    atasan: Record<string, number>;
    peer: Record<string, number>;
    bawahan: Record<string, number>;
  };
  overallScores: {
    amanah: number;
    kompeten: number;
    harmonis: number;
    loyal: number;
    adaptif: number;
    kolaboratif: number;
  };
  finalScore: number; // Avg of overall scores
}
